[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive", "env"] }
grid = "0.15.0"
lazy_static = "1.5.0"
nom = "7.1.3"
regex = "1.11.1"
simple-grid = "2.2.1"
