[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.21", features = ["derive", "env"] }
grid = "0.15.0"
itertools = "0.13.0"
nom = "7.1.3"
petgraph = "0.6.5"
rayon = "1.10.0"
regex = "1.11.1"
simple-grid = "2.2.1"
